### ISSUE TITLE
DOCX emitter doesn't set language for correction

### ISSUE THREAD

**Issue by doortokaos** [eclipse-birt/birt#1620] opened 2024-04-03 14:53 UTC
MS Word has functionalities to help the user writing correctly in a chosen language.
Since I use a German Version of MS Word, I don't know exactly the name in the English UI, but I think it might be called something like "Language for correction assistance". Here a screen of the menu in my word:
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/ae4bd580-3ad3-4c0b-a7b2-88cd9a86a8fa)

The language is always set to "English (US)" no matter in which language I create the report:
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/1995ea51-76d5-49bf-b498-2b7f906c0adf)

The report I used for the example is this (remove the .txt 😉):
[korrekturhilfe.rptdesign.txt](https://github.com/eclipse-birt/birt/files/14853989/korrekturhilfe.rptdesign.txt)

I generated the DOCX with the German locale active in the designer and no further settings on the report or eclipse.
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/563eda08-0518-4237-8f1d-7e30b7e0e1a3)

The designer is 4.15 Release all in one eclipse.

It would be nice, if the emitter could set the "Sprache für die Korrekturhilfe" to the language in which the report was created. So the user of the DOCX report won't have to set it every time manually after creating the report.

**Comment by doortokaos** [comment] 2024-04-03 16:02
@hvbtup thanks for the extensive reply.
It all makes sense and is more complicated as it seems to be.
I already thought that it can't be that easy because it would have been done already but I couldn't find information why it wasn't done already.

I wouldn't use the locale of the OS running BIRT as well, but I think using the locale in which the report is generated is a bit better than using nothing or defaulting to en_US. Since the user or report creator already set a locale for the complete report.

Since the perfect solution with a language for each text in the report seems rather complex, using a "better" locale for the complete document would be a step in the right direction in my opinion.

In my experience and user environment most documents contain only one language, so this could be an improvement, while not being perfect.

What do you think about this?

**Comment by speckyspooky** [comment] 2024-04-03 17:55
Yes, the tickets will be read :o)

The solution to verify if we could set the property for the whole documents sounds good to me.
The special thing is more a technical thing because the implementation of the docx-version is a mixture of a central library and own written source (from the original developers).
Therefore we cannot use the library-api directly and so we need a research to figure out is there a cetral property on document level.
(The latest MS Word versions support the language on document level and on paragraphs & tables.)

The otherone would be that the language value would be set through a user-property as a docx-emitter specific user-property.

**Comment by hvbtup** [comment] 2024-04-04 06:52
> The language is always set to "English (US)" no matter in which language I create the report

@doortokaos Can you find out if the en-US locale is specified somewhere explicitly in the (etracted) DOCX file structure or if this is just a default which Word assumes if there is no explicit entry?

> ... but I think using the locale in which the report is generated is a bit better ...

I'm strictly -1 on some kind of magic to determine the language if it is not explicitly defined in the rptdesign file.

> ...  using a "better" locale for the complete document would be a step in the right direction in my opinion.

Yes.

> The otherone would be that the language value would be set through a user-property as a docx-emitter specific user-property.

I don't think we need to extend the data model or use a UserProperty. The locale property of items should suffice.

A good starting point for where to look into the code should be the DocxWriter.java file. It's perfectly possible to write xml fragments directly into the output. I did this in our fork to support Word "Felder" (probably called "fields" in English Word?).

**Comment by speckyspooky** [comment] 2024-04-04 18:30
- Confirmed, the usage of a user-property with explicit language-code is the better way (see my comment).
- The language can be added on document and paragraph/table level, so we will be focused on document-level fort the first steps.
- The language will be entered with the tag <w:lang> and different attributes.
- 2 classes identified: Document (emitter.docx) and DocWriter (emitter.wpml)

According to the docx-definition, the value is a part of the assigned "style" of the according document/paragraph/table.

**Comment by doortokaos** [comment] 2024-04-05 12:29
> @doortokaos Can you find out if the en-US locale is specified somewhere explicitly in the (etracted) DOCX file structure or if this is just a default which Word assumes if there is no explicit entry?

@hvbtup here you go:
In the file word/styles.xml I find an entry
`<w:lang w:val="en-US" w:eastAsia="zh-CN" w:bidi="ar-SA" />`
somewhere beneath the `<w:docDefaults>` node:
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/6d34f0b3-cf5a-419b-94b3-8d69f2ee3e81)
When I replace "en-US" with "de-DE", save the styles.xml in the DOCX file with an archiver and open the changed DOCX with word, "German (Germany)" is set as language for the document.

So it seems, that BIRT sets en-US for the whole document as default.

The unaltered file created by BIRT for reference
[korrekturhilfe.docx](https://github.com/eclipse-birt/birt/files/14884679/korrekturhilfe.docx)

**Comment by speckyspooky** [comment] 2024-04-05 13:09
@doortokaos
Confirmed, my testing use according to my comment see above the style-element.

I'm with @hvbtup that not in every case the usage of the "Locale" is a good one
because we would change the default behavior and you won't have this behavior in every case.

My idea would be to test the following:
**1. I won't change the default behavior and default will be "en-US"**

2. if it is finished with succes my testing we could have 2 user-properties
2.A) user-property to configure explicit the language code
2.B) user-property to activate the "Locale" usage
2.C) if both values are active then the 2.A) will win because it is the explicit definition

3. validation will be implemented, is the language code invalid then fallback again to "en-US"

**Comment by hvbtup** [comment] 2024-04-05 13:25
@speckyspooky 

You misunderstood me. I'm +1 for using the locale property as defined inside the report.
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/eff6267c-d3b5-4ab9-9bf2-52a685c77a2c)

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/86a16da2-4495-475f-9558-b2b8c2be1833)

I'm -1 on guessing the local from the environment.

And I think that that existing default "en-US" is a minor bug (not everyone lives in the USA), so for me it's reasonable to change the behavior like this (changing the default behavior):

If the report property `locale` is explicitly set as shown above, then extract the language from there and write it into the DOCX file instead of "en-US". Otherwise, dont write the `w:lang` value into the DOCX.

**Comment by speckyspooky** [comment] 2024-04-05 14:12
Ok, understand than it was my fault.
Yes, we can use directly the "Locale" without user-properties.

**Comment by doortokaos** [comment] 2024-04-05 14:17
Thanks for your patience with me. I'm new to the whole GitHub-thing and trying my best.

@speckyspooky After clarifying your idea, I like it

**Comment by speckyspooky** [comment] 2024-04-05 20:49
I added PR #1627.

The enhancement include only the usage of the "report locale" without user-properties.
The fallback of "empty" or "invalid locale" will be the language "en", so we have the behavior like currently.

In my test cases I used "MS Word based on Office 365".

### Example 01: "fr_FR" value
![spell-check-fr_FR](https://github.com/eclipse-birt/birt/assets/41593722/1d7c6a6d-43e0-4547-a6e6-6a5038f776bd)

### Example 02: "it" value
![spell-check-it](https://github.com/eclipse-birt/birt/assets/41593722/df952035-85de-4b86-8970-e45402a9780e)

### Demo report
[docx_language.zip](https://github.com/eclipse-birt/birt/files/14890548/docx_language.zip)

**Comment by hvbtup** [comment] 2024-04-08 07:39
Thomas, I really like your example reports!

**Comment by speckyspooky** [comment] 2024-04-08 15:52
The enhancement is merged to the master with PR #1627

**Closed by speckyspooky** 2024-04-08 15:52 UTC
Labels: Enhancement
