### ISSUE TITLE
BIRT 4.14 creates an indent for grids in footer & header

### ISSUE THREAD

**Issue by reiner-killet** [eclipse-birt/birt#1547] opened 2024-01-19 12:52 UTC
Hi team,
I tested the last release of 2024-01-12. PDF is looking pretty good!
But regarding DOCX there is a change in behavior compared to 4.8:
We use grids in header & footer for easier positioning of pictures, page number etc.
In 4.8 the footer fits to the main area. See screenshot `No indentation of header and footer in 4 8 output DOCX.png`.
In 4.14 the footer moves to right. See screenshot `Indentation of header and footer in 4 14 output DOCX.png`.
I examined the footer and found out that BIRT creates a nested grid.
The inner grid results from my template.
The outer grid is added by BIRT.
The difference is that in 4.8 the outer grid hat a negative left indent and the inner grid had a positive indent of same amount.
In 4.14 the outer grid has no indent and the inner grid has a positive indent.
Next, I found a workaround:
The `Simple Master Page` has 2 properties in the `Advanced` slider:
- `Columns` which is set to `1 : inherited` as default.  
- `Column spacing` which is set to `12pt : inherited` as default.
When I change one of these values (`Columns` to `3`, or `Column spacing` to `0pt`) 4.14 behaves like 4.8.
Thereto, see screenshots `Indentation of header and footer in 4 14 - Workaround effect in XML.png` and `Indentation of header and footer in 4 14 - Workaround in designer`.
I do not understand the meaning of `Columns`. Set to `3` BIRT does not create 3 columns. 
Can you please check if this is a bug or maybe a feature somewhere else?
In my opinion it is a bug because a template with only default values should not lead to different indents in header, footer, and main area.
Thanks, Reiner
  
![Indentation of header and footer in 4 14 - Workaround effect in XML](https://github.com/eclipse-birt/birt/assets/95427074/214f2332-dc75-46c4-8313-d19008859299)
![Indentation of header and footer in 4 14 - Workaround in designer](https://github.com/eclipse-birt/birt/assets/95427074/b0d5483e-1f0d-4378-b2b8-64c9a750bb10)
![Indentation of header and footer in 4 14 output DOCX](https://github.com/eclipse-birt/birt/assets/95427074/f5889ec9-50ae-437f-9191-f3b32e9871e9)
![No indentation of header and footer in 4 8 output DOCX](https://github.com/eclipse-birt/birt/assets/95427074/e0ae5577-251e-4199-9234-52c24b290160)

**Comment by reiner-killet** [comment] 2024-01-19 12:57
Sorry for the inconvenience because of files names lost after commit. The above pictures should be in the sort order 3, 4, 1, 2.

**Comment by hvbtup** [comment] 2024-01-19 13:29
I don't know the purpose of "Columns" and "ColumnSpacing". Maybe these are relicts of some commercial BIRT version, to support e.g. a landscape page with two columns for the content.
Does anyone know more about them?

Regarding MS Word output, keep in mind that MS Word changed its behavior in the past years.
I know that because all of a sudden reports looked differently and the only thinh I changed was the version of MS Word used to open the document. The emitter now declares the output as MS Word 2016, to prevent Word from opening the document in compatibility mode. Your issue might be related to that change. Maybe you should investigate the Git logs of the Word emitter.

**Comment by speckyspooky** [comment] 2024-01-19 19:37
Short note to this topic, the effect of the indent of the header grid is given since version BIRT 4.10.
I agree with BIRT 4.8 the 2 grids have the same start indent but with 4.10 the header/footer got an additional indent.

**Comment by reiner-killet** [comment] 2024-01-22 08:23
Do you take this as bug or as feature?

 

Von: Thomas Gutmann ***@***.***> 
Gesendet: Freitag, 19. Januar 2024 20:37
An: eclipse-birt/birt ***@***.***>
Cc: Reiner Killet ***@***.***>; Author ***@***.***>
Betreff: Re: [eclipse-birt/birt] BIRT 4.14 creates an indent for grids in footer & header (Issue #1547)

 

Short note to this topic, the effect of the indent of the header grid is given since version BIRT 4.10.
I agree with BIRT 4.8 the 2 grids have the same start indent but with 4.10 the header/footer got an additional indent.

**Comment by merks** [comment] 2024-01-22 08:46
@reiner-killet 

Replying to a GitHub email as a way to post to an issue is really ugly, creating a lot of noise.  Please use the web interface via a browser instead.

https://github.com/eclipse-birt/birt/issues/1547

**Comment by reiner-killet** [comment] 2024-01-22 08:53
I was first thinking about signing in but then read this in the signature of all of your e-mails: 
![grafik](https://github.com/eclipse-birt/birt/assets/95427074/5f010008-e4b6-4496-8425-af779e941a86)
Next time :-)

**Comment by reiner-killet** [comment] 2024-01-22 16:30
Hi @speckyspooky : This is weird: I'm not able to reproduce my own workaround of 3 days ago.
Can you imagine any workaround to get header and footer tables left-aligned?

**Comment by speckyspooky** [comment] 2024-01-22 21:16
I started different debug sessions but cuurently I didn't find the cause of the indent.
The workaround would be really strange to wrap the content into a grid and work with margin (left hand & right hand side).

**Comment by speckyspooky** [comment] 2024-01-24 23:14
I spent more time to debug the behavior and the padding of header-/footer-grids is based on an additional container-table around the grid. The topic is that BIRT create the according container table but without instruction of the margin himself.
Therefore a default margin will be used and this margin isn't zero (, it is a kind of MS Office standard value).

**Long text, short story**
The container-table must have a margin of zero.

I will create a PR for this topic.

**Comment by speckyspooky** [comment] 2024-01-24 23:27
A fix is provided with PR #1552 (small screen example added into the communication messages)

**Comment by speckyspooky** [comment] 2024-01-25 20:09
The issue is fixed with the above mentioned PR.

**Closed by speckyspooky** 2024-01-25 20:09 UTC
Labels: BugFix
