### ISSUE TITLE
BIRT 4.14 does not properly scale picture like in 4.8 with DOCX output 

### ISSUE THREAD

**Issue by reiner-killet** [eclipse-birt/birt#1549] opened 2024-01-24 16:42 UTC
Hi, 
we are using scanned signatures in letters with the option "Image file in shared ressources".
These images are normally located in a grid.
The cell has a static height. 
The picture brings along a certain height and width and a resolution in dpi.
In former versions you could set either target height or target width (not both) to make BIRT scale up or down the picture.
This does not work anymore with DOCX output.
Enclosed please find a sample picture.
![CPD_SND_SGN_UNTERSCHLEHMANN](https://github.com/eclipse-birt/birt/assets/95427074/2b2299ca-48e2-40fb-9849-4b63f623832d)
When you double-click this picture you can see the ratio which should be achieved.
It cannot be reached with the DOCX emitter.
It seems that the DOCX emitter adjusts the missing value in a way that it finally gets a square.
Do you additionally need a small template for testing?
Thanks, Reiner

**Comment by speckyspooky** [comment] 2024-01-24 19:16
Yes, please add an example because there are many ways to add images 
and I know on of your last issues you used an own way based on HTML to add the images.

Therefore please add.
Have you tested the output on other BIRT versions may be BIRT 4.9 to figure out with which version the change was added to BIRT?

**Comment by speckyspooky** [comment] 2024-01-24 20:29
I tested the behavior in detail and can confirm that this is a changed behavior with BIRT4.14 and I qualify that as bug.
I will create a PR for that.

**Comment by speckyspooky** [comment] 2024-01-24 21:49
Fix provided with PR #1551

**Comment by speckyspooky** [comment] 2024-01-25 20:09
The issue is fixed with the above mentioned PR.

**Closed by speckyspooky** 2024-01-25 20:09 UTC
Labels: BugFix
