### ISSUE TITLE
An error occurs when creating an XLS/XLSX file

### ISSUE THREAD

**Issue by hypn0chka** [eclipse-birt/birt#1455] opened 2023-10-23 08:56 UTC
An error occurs when generating XLS/XLSX files:
 "java.lang.IllegalStateException: Cannot add merged region A2:E2 to sheet because it overlaps with an existing merged region (A2:E2).".

There was no such error in versions up to 4.8. It looks like there have been changes to the Spudsoft emitter.
Can you fix this error? I can't do this myself because I don't know Java.

[xls_xlsx_error.zip](https://github.com/eclipse-birt/birt/files/13068112/xls_xlsx_error.zip)

**Comment by speckyspooky** [comment] 2023-10-23 18:16
I have checked your test-report and the issue with the merged cells occure with version BIRT 4.6 XLSX-Spudsoft.
And with all later versions to, so it seems not a new bug this must be an older one.

(I tested BIRT 4.6, BIRT 4.8, BIRT 4.14 - all versions have the same behavior.)

**Comment by speckyspooky** [comment] 2023-10-23 18:34
The is a workaround (may be) because I checked your test-report and added a text to your empty-text (type: auto) and afterwards I was able to create your report:

![2023-10-23 20_25_21-workspace_rep - C__Users_gutma_Downloads_xls_xlsx_error_xls_xlsx_error rptdesign](https://github.com/eclipse-birt/birt/assets/41593722/23762bf4-bd14-45c4-8b51-cd0d92b9cef6)

The effect is only given on a row with 1 overspan of 2 cells and no text element or label is available with a value.

**Comment by ivkina** [comment] 2023-10-24 22:08
We are also having the same issue/error in some reports (others work fine). 

Could you please provide a little bit more details on possible workarounds? Is the issue fixed in the latest version of BIRT? We are using verison 4-10 (org.eclipse.birt.runtime_4.10.0-20220721.jar).

Here is the error:
Cannot add merged region B2:B3 to sheet because it overlaps with an existing merged region (A2:K2).
StackTrace:
org.apache.poi.xssf.usermodel.XSSFSheet.validateMergedRegions(XSSFSheet.java:486)
org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:413)
org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:367)
uk.co.spudsoft.birt.emitters.excel.StyleManagerUtils.extendRows(StyleManagerUtils.java:1082)
uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableRowHandler.interruptRow(AbstractRealTableRowHandler.java:186)
uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableRowHandler.endRow(AbstractRealTableRowHandler.java:63)
uk.co.spudsoft.birt.emitters.excel.ExcelEmitter.endRow(ExcelEmitter.java:331)

**Comment by speckyspooky** [comment] 2023-10-25 04:29
@ivkina Could you please provide an example report?

I have tried a first fixing but this will only avoid the issue of case 1) and your case 2) is the more complex merged-cell case.
The main issue is that the excel-emitter fetch a "row" which has no text value finally (condition 1) and the row includes a merged cell (condition 2). In this constellation the merged cell method will be called twice but this cause the error of this issue ticket.

In you case it seems that you have 2 rows which merged across merged cell (in a row 2) A2:K2 and merged cell B2:B3 in differend rows (row 2 & 3) and so you got the conflict because it is not allowed to have such cross cell merge.
In your case the issue is the conflict of cell B2 which is used twice of cell merge which is not possible.

It could be that your "row 2" has finally no text and so the internal row calculation goes wrong but there I would need an example of you.

And no, the issue isn't fixed because it is a complex case over all situations.

Woraround:
Try to avoid empty rows by using an unvisible character like "&nbsp;" (none-breaking-space) to keep the row.
(In the case above it was an option.)

**Comment by ivkina** [comment] 2023-10-27 01:56
Thanks for your detailed reply! Yes, we use this technique of adding empty rows of fixed height to the report to achieve more controlled presentation and output. Let me check if condition 2 (merged cells) is also in place. The issue occurs with some reports but not with others. The problem is that we have more than 500 reports. Most of them are pixel-perfect/size-perfect page based layout so "empty rows" technique is used in a lot of places.

**Comment by speckyspooky** [comment] 2023-10-29 10:54
@ivkina I would be able to fix the exception but there is currently another issue because due to the merge, empty rows will be deleted in some special cases. And this cause your exception.

The workaround in your case would be if you use "dynamic text" or other kind of dynamic generated text-content then avoid that the result is empty or an empty string.
If you have NULL or an empty string you can add for example a "Non-Breaking-Space" (= &nbsp; HTML-entity or key-board-code ALT+160) as result value then the line won't be removed because it is not empty and you got your row with your merged cells.

Currently I have no glu where the method is which cause the removed row.

**Comment by speckyspooky** [comment] 2023-10-29 13:01
@hypn0chka  & @ivkina 
I found the reason of the conflict and it is the combination of 2 different topics of the Spudsoft-Excel-Generator.
- Reason 1 is the row handling default of excel which removes blank rows by default.
- Reason 2 is the merged cells of excel.
And if a blank row with merge was detected like removeable it will be removed but the merge cells registered already which cause the error at the next line with merged cells.

The quick solution to fix it is to set on report level the user property "ExcelEmitter.RemoveBlankRows":
```
ExcelEmitter.RemoveBlankRows => Boolean => false
```
This configuration avoid for excel that blank rows will be removed (default is true).

**Comment by ivkina** [comment] 2023-10-30 14:28
@speckyspooky 
Thanks again for sharing the solution. Appreciate that. Is this property ExcelEmitter.RemoveBlankRows already as a standard property or you have to create it yourself under User Properties->Add? So, the emiiter code is already aware of this "undocumented" property and it will behave accordingly? Or do I need a new version of emmitter that honors the property? Thank you

**Comment by ivkina** [comment] 2023-10-30 16:25
@speckyspooky 
I tried adding ExcelEmitter.RemoveBlankRows=false at report level (user properties) but it did not do the trick. Please, see attached report design and the libraries. You won't be able to run it since it requires j2ee/ejb runtime to feed the data but you should be able to see the design. Thanks again!
[excel-err.zip](https://github.com/eclipse-birt/birt/files/13207447/excel-err.zip)

error:
ct 30, 2023 11:58:47 AM org.eclipse.birt.report.engine.api.impl.EngineTask handleFatalExceptions
SEVERE: An error happened while running the report. Cause:
java.lang.IllegalStateException: Cannot add merged region B2:B3 to sheet because it overlaps with an existing merged region (A2:K2).
	at org.apache.poi.xssf.usermodel.XSSFSheet.validateMergedRegions(XSSFSheet.java:486)
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:413)
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:367)
	at uk.co.spudsoft.birt.emitters.excel.StyleManagerUtils.extendRows(StyleManagerUtils.java:1082)
	at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableRowHandler.interruptRow(AbstractRealTableRowHandler.java:186)
	at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableRowHandler.endRow(AbstractRealTableRowHandler.java:63)
	at uk.co.spudsoft.birt.emitters.excel.ExcelEmitter.endRow(ExcelEmitter.java:331)
	at org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.endRow(HTMLTableLayoutEmitter.java:540)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.endContent(ContentEmitterUtil.java:107)
	at org.eclipse.birt.report.engine.layout.html.buffer.DummyPageBuffer.endContainer(DummyPageBuffer.java:62)
	at org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.end(HTMLStackingLM.java:39)
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:134)
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66)
	at org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.java:27)
	at org.eclipse.birt.report.engine.layout.html.HTMLTableBandLM.layoutChildren(HTMLTableBandLM.java:62)
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133)
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66)
	at org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.java:27)
	at org.eclipse.birt.report.engine.layout.html.HTMLRepeatHeaderLM.layoutChildren(HTMLRepeatHeaderLM.java:54)
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133)
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66)
	at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:92)
	at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:97)
	at org.eclipse.birt.report.engine.api.impl.RenderTask$PageRangeRender.render(RenderTask.java:569)
	at org.eclipse.birt.report.engine.api.impl.RenderTask.render(RenderTask.java:273)

**Comment by speckyspooky** [comment] 2023-10-30 19:35
@ivkina
I have checked your report and it is a complex report so I can only say thet you have used the user property correctly. 
I use the property since BIRT 4.6 and it is a standard property of the Spudsoft-excel. And yes there are some more undocumented properties.

But due to the complex structure and the unclear behavior what your engine does it is not possible to say why the property not work. On my simple demo reports it works very fine.

I will try to create a fix for that. But I don't know at the end whether the result of the xlsx genereation is the required result according you dynamic & complex structure.

**Comment by ivkina** [comment] 2023-10-30 19:50
@speckyspooky 
Understood. Thank you...also noted that the same report download to xlsx works just fine when running on BIRT 4.9 runtime  (org.eclipse.birt.runtime_4.9.0-20190523) but fails with this "overlap" error when running on BIRT 4.10-11 (org.eclipse.birt.runtime_4.13.0-20230302). Maybe that helps...TY

**Comment by ivkina** [comment] 2023-10-30 20:25
@speckyspooky - I can test it if you want me to. Can I grab the fix for the version? We are running  BIRT 4 - 11 (org.eclipse.birt.runtime_4.13.0-20230302)

**Comment by speckyspooky** [comment] 2023-10-30 20:28
The fix run through our internal quality check so it needs a will till it is available under the BIRT version 4.14.
You cannot grab the fixed version before.

**Comment by ivkina** [comment] 2023-10-30 20:33
@speckyspooky - noted. we will give it a try once 4-14 is available. Our users use dowload to xlsx option quite a lot and this is a painfull issue for them...especially, when eveything worked in previous version of BIRT 4-6. Thanks

**Comment by speckyspooky** [comment] 2023-10-31 19:15
The fix will be available with BIRT 4.14.

**Closed by speckyspooky** 2023-10-31 19:15 UTC
Labels: BugFix

**Comment by ivkina** [comment] 2023-10-31 19:23
@speckyspooky  - will test once available. thanks again!

**Comment by merks** [comment] 2023-11-01 15:21
It's available now:

https://download.eclipse.org/birt/updates/nightly/latest/

But maybe you are specifically asking for when a release will be available?

I don't speak for the project, but I'm hoping that BIRT will release right around the same time frame as when the SimRel 2023-12 release is available on December 6th:

https://github.com/eclipse-simrel/.github/blob/main/wiki/SimRel/2023-12.md

**Comment by speckyspooky** [comment] 2023-11-01 19:25
@wimjongman & @merks 
Due to the usage of the new eclipse version 2023-12 which will be get the final release on December 6th we should directly afterwards close all changes and publish the BIRT 4.14.

Then we are 2 month later like the original plan of BIRT 4.14. I need really the new version because it is the base of my use platform.
But my supplier won't allow to use a BIRT-built without the "final status" / ""release status".

@wimjongman What is your plan?

**Comment by wimjongman** [comment] 2023-11-01 19:40
Let's discuss here: https://github.com/eclipse-birt/birt/discussions/1254

**Comment by ivkina** [comment] 2024-06-04 21:54
@speckyspooky 
I was able to verify your fix with version 4.15 jdk1.21 and oracle weblogic 14.1.2 (beta) - seems to be working fine. thanks!

**Comment by ivkina** [comment] 2024-06-05 19:18
@speckyspooky  - I have a question if you have a few more minutes regarding this fix you did in 4.14-4.15 versions. My understanding is that you are not going to implement the same fix in 4.13, and BIRT 4.14-15 requires a minimum of Java 17 to run. If that's the case, we might want to implement the fix ourselves in version 4.13. Unfortunately, we are kind of 'stuck' on a Java 11 baseline for at least another 6 months due to Oracle WebLogic/JDK limitations and the delay in WebLogic support for JDK 17 and up. At the same time, our clients are very "noisy" about this Excel conversion error.

How involving is this fix? Are there a lot of dependencies? Would it be possible/easy to port the code changes you made into the 4.13 Excel emitter?
Thank you

**Comment by speckyspooky** [comment] 2024-06-06 18:28
The topic is that with BIRT 4.14 we changed the dependencies of the internally apache POI library from 4.1.1 (BIRT 4.13) to version 5.2.4. So yes, the change of the whole environment was a stronger change.

The only think what you can try is that you extract the 2 classes from BIRT 4.14
C:\BIRT_4.14\eclipse\plugins\uk.co.spudsoft.birt.emitters.excel_4.14.0.v202311210608\uk\co\spudsoft\birt\emitters\excel\handlers

and replace it on BIRT 4.13. The change himself doesn't use dependencies which doesn't exists in BIRT 4.13/POI 4.1.1.

**Comment by ivkina** [comment] 2024-06-06 20:46
just to confirm - these 2 classes, correct?
uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableRowHandler.java

![image](https://github.com/eclipse-birt/birt/assets/17771801/0ee70b82-9fdf-42ad-b3be-4c1a6d17914b)

**Comment by ivkina** [comment] 2024-06-06 21:38
looks like I need more classes....getting nosuchmethod error

SEVERE: Error happened while running the report.
java.lang.NoSuchMethodError: uk.co.spudsoft.birt.emitters.excel.AreaBorders.create(IIIILuk/co/spudsoft/birt/emitters/excel/BirtStyle;)Luk/co/spudsoft/birt/emitters/excel/AreaBorders;
	at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableHandler.startTable(AbstractRealTableHandler.java:117)
	at uk.co.spudsoft.birt.emitters.excel.handlers.TopLevelTableHandler.startTable(TopLevelTableHandler.java:44)
	at uk.co.spudsoft.birt.emitters.excel.handlers.PageHandler.startTable(PageHandler.java:351)
	at uk.co.spudsoft.birt.emitters.excel.ExcelEmitter.startTable(ExcelEmitter.java:297)
	at org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.startTable(HTMLTableLayoutEmitter.java:334)
