### ISSUE TITLE
Batik URL error when loading external image

### ISSUE THREAD

**Issue by msimanga** [eclipse-birt/birt#1841] opened 2024-08-07 15:48 UTC
I use the ReportEngine from the command line to generate PDF documents for clients. Different clients have different colour themes for their graphs. I use images as background colours for the graph series. This works well in BIRT version from 2018.  The SeriesPalette XML looks something like this 

`<SeriesPalette>
          <Entries xsi:type="attribute:Image">
            <URL>file:///C:/hiu/birt/disease_auths/images/live/colour1.png</URL>
            <source>static</source>
          </Entries>`

I am getting the following error when running BIRT

> Caused by: org.apache.batik.bridge.BridgeException: Could not access the current document URL when trying to load an external resource file:/C:/hiu/birt/disease_auths/images/live/colour1.png. The external resource will not be loaded as it is not possible to verify it comes from the sam
e location as the document.

I did some research which led me to this [StackOverflow answer](https://stackoverflow.com/questions/77414977/batik-bridge-1-17-jar-could-not-access-external-resource).  Seems this was a change to Batik for security reasons, any chance his can be made into a flag or option that one can check.

**Comment by speckyspooky** [comment] 2024-08-07 17:39
We would need a small example report from your side with the grafik.
But without any external data source reference that we can reproduce the topic and have the same starting point like you.

Yes, I read the StackOverflow-hint and it must be checked.
The topic is that we use BATIK at different locations of the whole project not onyl at PDF size.

**Comment by hvbtup** [comment] 2024-08-08 06:53
Maybe you can solve this by using a relative path which must not contain upwards references `..`.

**Comment by speckyspooky** [comment] 2024-08-14 14:14
For your suggestions, have you tried to use the CSS-styles of the report which can be manipulated  through a fetch based on the style name and changed to the according CI. (I use this option for my specific division-CIs).

And a question could you please add a screen where you call the image dialog because I'm not sure which option you mean/where the dialog was called from.

**Comment by speckyspooky** [comment] 2024-08-17 14:39
The change of the embedded external resource is merged to the master with PR #1857.

**Comment by speckyspooky** [comment] 2024-08-17 14:49
@msimanga 

There is an additional option instead of the image option for the palett-color which is a good solution
you would be able to use scripting of the color. The screen below shows the original chart color "orange" which will be changed via script to "red".
The scripts are included on the chart at method "onRender()" - my (small) example is attached.
So you would be able to use a parameter to set the necessary colors (, my example is without parameters but you get the scripts for the color setting).

### Chart, dynamic color change (script)
![grafik](https://github.com/user-attachments/assets/6985b2ca-605a-4469-9764-ed7dbbf4f080)

### Chart example with scripted color
[chart_image.zip](https://github.com/user-attachments/files/16645287/chart_image.zip)

**Comment by speckyspooky** [comment] 2024-08-20 16:08
I will close this ticket.
The change is available and aditional hints available too.

Don't hesitate to aks if there are some further detailed questions.

**Closed by speckyspooky** 2024-08-20 16:08 UTC
Labels: Enhancement, Support
