### ISSUE TITLE
DOCX: Unreadable Content in Word Report Following Update to 4.18.0 - caused by grid-in-grid-structures

### ISSUE THREAD

**Issue by tameergh1** [eclipse-birt/birt#2010] opened 2024-12-15 10:10 UTC
We are encountering an issue when opening a World Report after updating to version 4.18.0.
![image](https://github.com/user-attachments/assets/0c628c60-7a78-4e6b-87aa-d85025c19921)
 Prior to the update, we were using version 4.17.0, and everything worked as expected.

**Comment by merks** [comment] 2024-12-15 10:21
Anyone wanting to investigate this problem will need to be able to reproduce it...

**Comment by speckyspooky** [comment] 2024-12-15 11:29
The version BIRT 4.18 includes bigger changes for docx-output and according to the note of Ed we need an example
of the report without external dependencies like DB-access and external libraries.

The main change with BIRT 4.18 is the handling of formatting grid for label-, text-, dynamic-text-elements and grid-table-cell hadling.

But the BIRT 4.18 includes all options to get the orignal handling of BIRT 4.17.
Fort that you can use the "advanced register" of the report or specialized user properties.

Nevertheless your example woul help to fix problems according to your reports.

### Documentation of BIRT 4.18 Docx-"User Properties"
[https://github.com/eclipse-birt/birt/blob/6fa78f7c4318204453e10790c5ecc7ecb1167fda/engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/README.md](url)

**Comment by tameergh1** [comment] 2024-12-15 12:11
Please find the report attached.
[New report test.docx](https://github.com/user-attachments/files/18140319/New.report.test.docx)

**Comment by speckyspooky** [comment] 2024-12-15 12:54
We need the original ".rptdesign"-file for the error tracking to fetch the issue.
The output isn't helpfull in this situation. Could you please provide an design-file-example with the issue.

**Comment by tameergh1** [comment] 2024-12-15 15:39
File type is not supported 
I added it as a txt
[Template.txt](https://github.com/user-attachments/files/18141039/Template.txt)

**Comment by speckyspooky** [comment] 2024-12-15 15:57
The rptdesign must be added to a zip-file and this can be uploaded.
I have used your file and renamed it to ".rptdesign" but I get XML-errors (see below), the layout-designer cannot be opened and the report cannot be created with your current test version.

Please remove all external dependencies. There is a library listed "CCP.rptlibrary" and some other external references to CCP & Oracle - see below.

Can you please remove all dependencies CCP and Oracle and upload the report at a zip file.
Nobody would be able to support you if we have such external references at the report, this is specific to your company.

### XML errors
![grafik](https://github.com/user-attachments/assets/98a4c470-6ef2-4445-89e3-15fe84a118ac)

### External references
![grafik](https://github.com/user-attachments/assets/7043da72-8203-43b5-921b-55037858c94b)

![grafik](https://github.com/user-attachments/assets/b596c730-a5b0-4bb1-bc1c-cc37a954909a)

**Comment by speckyspooky** [comment] 2024-12-15 16:02
I fixed the issue on the string at line 284 - according to the XML message and now I get so much external reference messages,
therefore we would need a plain test:

![grafik](https://github.com/user-attachments/assets/819e46c1-91a7-4ce3-aba7-770921ce7016)

**Comment by speckyspooky** [comment] 2024-12-15 16:47
Next try, I got your report running and the problem is the grid-in-grid structure which cause an error at the internal docx-structur.
Currently, I don't know why, I have to investigate deeper.

Woraround you can set the following option on report-level "register: advanced",
to reactivate the original handling an then you will get the structure-handling of the structure from BIRT 4.17.

![grafik](https://github.com/user-attachments/assets/a1b8d059-67ce-4ea4-9652-dcb8fecc3b2c)

**Comment by speckyspooky** [comment] 2024-12-15 21:19
The last note for today, I added a fix that the problem will be fixed PR #2011.

The core topic is that excel requires after each table an empty paragraph.
If htere are many tables/grids cascaded then it isn't so easy for the user to work with the created docx-documents.

But currently there is no perfect solution for all therefore the necessary paragraphs will be created like before.
The option to avoid the empty paragraphs must be activated through the user explicitly.

**Comment by tameergh1** [comment] 2024-12-16 09:19
What do u mean by set "register: advanced" in report level ?
in report design ?
or report props ?

**Comment by speckyspooky** [comment] 2024-12-16 12:25
If you take a look into my last screen you see the configuration.

You mark the report-root-tag, than you activate the property editor tab, there you select the register-button "Advanced" and there is the property-category "Emitter Word configuration" and there you can change the "text element"-handling that the original layout-tables will be used according to BIRT 4.17.

**Comment by tameergh1** [comment] 2024-12-16 13:54
Thank you for the detailed explanation! Just to clarify, I am using the BIRT engine to generate the reports. Could you please guide me on how exactly I should configure the 'Emitter Word configuration' property to ensure that the original layout tables are used correctly in BIRT 4.17?

**Comment by speckyspooky** [comment] 2024-12-16 20:01
The configuration will be done on your reports with the BIRT-designer.
The "Emitter Word configuration" has the option "Text element, use layout-grid for margin & padding". The default of this option is "false". If you set the option to "true" then each element will get the orignal grid handling according to BIRT 4.17.

**Closed** 2024-12-16 21:11 UTC
Labels: BugFix

**Comment by tameergh1** [comment] 2024-12-17 12:42
I tried adding those lines to the .rptdesign file, but none of them solved the issue. Maybe I'm adding them incorrectly.

**Comment by tameergh1** [comment] 2024-12-17 14:41
Can u generate and send the .rptdesign file after changing this property?
thanks

**Comment by speckyspooky** [comment] 2024-12-17 19:41
Questoin, why you use the XML-structure of the report and try to change it?
Because I talk about the usage of the designer and not to work with the XML-structure directly.
With the designer you can change the property very easy:

![grafik](https://github.com/user-attachments/assets/37277ff4-0fb4-4fa9-aeeb-2590899529d7)

If you want to change it really on XML-level here are the first lines of such report and the property key is "wordWrappedTableForMarginPadding" and this tag must be added to your report.

By the way, the latest nightly build is available with the fix of that issue.

```
<report xmlns="http://www.eclipse.org/birt/2005/design" version="3.2.26" id="1">
    <property name="createdBy">Eclipse BIRT Designer Version 4.19.0.qualifier</property>
    <text-property name="title" key="title.key">Param Optimization 2.2</text-property>
    <simple-property-list name="includeResource">
        <value>translation</value>
    </simple-property-list>
    <property name="units">mm</property>
    <property name="iconFile">/templates/blank_report.gif</property>
    <property name="bidiLayoutOrientation">ltr</property>
    <property name="imageDPI">96</property>
    <property name="wordWrappedTableForMarginPadding">true</property>
```

**Comment by tameergh1** [comment] 2024-12-18 10:18
Hi,
I added the property to the report and still getting the same issue!!!

**Comment by speckyspooky** [comment] 2024-12-18 11:30
Have you added the poperty with the Designer or plain on XML-Level?

Could you please Provider the test report as zip-file.

Max be you can test the nigthly built of BIRT 4.19

**Comment by tameergh1** [comment] 2024-12-18 13:23
I added <property name="wordWrappedTableForMarginPadding">true</property> 
to the report on XML-Level

**Comment by speckyspooky** [comment] 2024-12-18 13:59
What will be Happen If you use the Designer?

**Comment by speckyspooky** [comment] 2024-12-18 19:11
@tameergh1
Attached you will find your test report with issue and my version with the configured property-value.
I used the BIRT-designer to setup the property. The changed test report create a docx-document without the issue and word message.

### original test report - docx with issue:
[template-test-without-flag-with-issue.zip](https://github.com/user-attachments/files/18187784/template-test-without-flag-with-issue.zip)

### changed test report - docx without issue:
[template-test-with-flag-without-issue.zip](https://github.com/user-attachments/files/18187785/template-test-with-flag-without-issue.zip)

**Comment by tameergh1** [comment] 2024-12-19 07:07
I changed the design version to 3.2.26
and the designer to 4.18.0.v202411161754
and I'm getting
![image](https://github.com/user-attachments/assets/14d47e5c-c30b-4808-bdc0-d93d246bfb07)

**Comment by speckyspooky** [comment] 2024-12-19 07:12
Take a look into my läßt message and the examples.

You cannot change the Version number and think it will change the behavior. This will not work.

**Comment by eobrienPilz** [comment] 2025-05-02 11:02
@speckyspooky Our report generation is failing for wordml with what looks to be this same issue. Would you mind providing a code example showing how to set the report-level "register: advanced" option ?

**Comment by eobrienPilz** [comment] 2025-05-06 10:20
Yes, that works. I also needed to set the first option to true for the list element. Is the 4.19 fix, just setting these values by default ? I am wondering if there will be any additional action needed by us when the time comes to move up.

**Comment by speckyspooky** [comment] 2025-05-06 19:20
Yes, the list element option will be set to "true" as new default value.
