### ISSUE TITLE
Excel Based reports are not getting generated after version 4.10 of BIRT.

### ISSUE THREAD

**Issue by poonam197shukla** [eclipse-birt/birt#1268] opened 2023-04-16 19:59 UTC
Error : java.lang.NullPointerException: Cannot invoke "com.binaryfortis.data.xls.XlsHelper$Range.getRow(int)" because "this.range" is null.
Can anyone please suggest a way to handle this scenario.

**Comment by speckyspooky** [comment] 2023-04-16 20:08
To assist you we would need a little bit mor information.
Which version do you need exactly BIRT 4.10 - 4.13 or have you all versions tested?
If you could provide a small example without database & library dependencies we are able to reproduce and debug the issue.
ALso the full stack trace would be helpful.

Is the mentioned class "com.binaryfortis.data.xls.XlsHelper" a special provider / programmed extension from your side
bacause "com.binaryfortis" isn't part of BIRT.

**Comment by poonam197shukla** [comment] 2023-04-17 05:54
This issue we are facing from BIRT 4.10 onwards (Mainly we checked in 4.10, 4.12 and 4.13).

yes "com.binaryfortis.data.xls.XlsHelper" is a provider from our side.

Any dependencies related to excel based reports which has been added in later versions? as we got one exception related to poi API's as well.

**Comment by poonam197shukla** [comment] 2023-04-17 06:10
Another set of logs we found in investigation:
org.eclipse.birt.report.engine.script.internal.ScriptExecutor addException
WARNING: Invalid javascript expression: ReferenceError: "GMS_init" is not defined. (/report/method[@name="initialize"]#1)
org.eclipse.birt.report.engine.api.EngineException: Invalid javascript expression: ReferenceError: "GMS_init" is not defined. (/report/method[@name="initialize"]#1)
	at org.eclipse.birt.report.engine.script.internal.ScriptExecutor.addException(ScriptExecutor.java:213)
	at org.eclipse.birt.report.engine.script.internal.ReportScriptExecutor.handleInitialize(ReportScriptExecutor.java:82)
	at org.eclipse.birt.report.engine.api.impl.EngineTask.loadDesign(EngineTask.java:1565)
	at org.eclipse.birt.report.engine.api.impl.DataExtractionTaskV1.<init>(DataExtractionTaskV1.java:216)
	at org.eclipse.birt.report.engine.api.impl.DataExtractionTask.<init>(DataExtractionTask.java:52)
	at org.eclipse.birt.report.engine.api.impl.ReportEngineHelper.createDataExtractionTask(ReportEngineHelper.java:403)
	at org.eclipse.birt.report.engine.api.impl.ReportEngine.createDataExtractionTask(ReportEngine.java:474)
	at com.binaryfortis.birt.oda.base.SourceRPT.getExtractTask(SourceRPT.java:336)
	at com.binaryfortis.birt.oda.base.SourceRPT.getResultSet(SourceRPT.java:428)
	at com.binaryfortis.birt.oda.base.SourceRPT.parseHeaders(SourceRPT.java:221)
	at com.binaryfortis.birt.oda.base.SourceRPT.ensureMetaOpen(SourceRPT.java:480)
	at com.binaryfortis.birt.oda.base.Source.getRSetMeta(Source.java:656)
	at com.binaryfortis.birt.oda.base.SourceRPT.getRSetMeta(SourceRPT.java:672)
	at com.binaryfortis.birt.oda.rptdoc.Query.getMetaData(Query.java:659)
	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaQuery.doGetMetaData(OdaQuery.java:423)
	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaQuery.getMetaData(OdaQuery.java:390)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getRuntimeMetaData(PreparedStatement.java:369)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getProjectedColumns(PreparedStatement.java:344)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.declareCustomColumn(PreparedStatement.java:1092)
	at org.eclipse.birt.data.engine.executor.DataSourceQuery.addCustomFields(DataSourceQuery.java:621)
	at org.eclipse.birt.data.engine.executor.DataSourceQuery.prepareColumns(DataSourceQuery.java:388)
	at org.eclipse.birt.data.engine.executor.DataSourceQuery.prepare(DataSourceQuery.java:337)
	at org.eclipse.birt.data.engine.impl.PreparedOdaDSQuery$OdaDSQueryExecutor.prepareOdiQuery(PreparedOdaDSQuery.java:565)
	at org.eclipse.birt.data.engine.impl.QueryExecutor.prepareExecution(QueryExecutor.java:347)
	at org.eclipse.birt.data.engine.impl.PreparedQuery.doPrepare(PreparedQuery.java:388)
	at org.eclipse.birt.data.engine.impl.PreparedDataSourceQuery.produceQueryResults(PreparedDataSourceQuery.java:164)
	at org.eclipse.birt.data.engine.impl.PreparedDataSourceQuery.execute(PreparedDataSourceQuery.java:153)
	at org.eclipse.birt.data.engine.impl.PreparedOdaDSQuery.execute(PreparedOdaDSQuery.java:172)
	at org.eclipse.birt.report.data.adapter.impl.DataRequestSessionImpl.execute(DataRequestSessionImpl.java:596)
	at org.eclipse.birt.report.engine.api.impl.GetParameterDefinitionTask.executeQuery(GetParameterDefinitionTask.java:529)
	at org.eclipse.birt.report.engine.api.impl.GetParameterDefinitionTask.getResultSetOfCascadingGroup(GetParameterDefinitionTask.java:856)
	at org.eclipse.birt.report.engine.api.impl.GetParameterDefinitionTask.getChoicesFromParameterGroup(GetParameterDefinitionTask.java:788)
	at org.eclipse.birt.report.engine.api.impl.GetParameterDefinitionTask.getCascadingParameterList(GetParameterDefinitionTask.java:482)
	at org.eclipse.birt.report.engine.api.impl.GetParameterDefinitionTask.doGetSelectionList(GetParameterDefinitionTask.java:408)
	at org.eclipse.birt.report.engine.api.impl.GetParameterDefinitionTask.getSelectionList(GetParameterDefinitionTask.java:381)
	at org.eclipse.birt.report.engine.api.impl.GetParameterDefinitionTask.getSelectionListForCascadingGroup(GetParameterDefinitionTask.java:600)
	at org.eclipse.birt.report.service.BirtViewerReportService.getSelectionListForCascadingGroup(BirtViewerReportService.java:624)
	at org.eclipse.birt.report.presentation.aggregation.parameter.ComboBoxParameterFragment.getParameterSelectionListForCascadingGroup(ComboBoxParameterFragment.java:103)
	at org.eclipse.birt.report.presentation.aggregation.parameter.ComboBoxParameterFragment.prepareParameterBean(ComboBoxParameterFragment.java:76)
	at org.eclipse.birt.report.presentation.aggregation.parameter.ScalarParameterFragment.doService(ScalarParameterFragment.java:85)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.service(AbstractBaseFragment.java:74)
	at org.apache.jsp.webcontent.birt.pages.parameter.ParameterGroupFragment_jsp._jspService(ParameterGroupFragment_jsp.java:212)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.service(AbstractBaseFragment.java:79)
	at org.apache.jsp.webcontent.birt.pages.dialog.ParameterDialogFragment_jsp._jspService(ParameterDialogFragment_jsp.java:176)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.service(AbstractBaseFragment.java:79)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.callBack(AbstractBaseFragment.java:100)
	at org.apache.jsp.webcontent.birt.pages.dialog.DialogContainerFragment_jsp._jspService(DialogContainerFragment_jsp.java:316)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.service(AbstractBaseFragment.java:79)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.callBack(AbstractBaseFragment.java:100)
	at org.apache.jsp.webcontent.birt.pages.layout.SidebarFragment_jsp._jspService(SidebarFragment_jsp.java:134)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.service(AbstractBaseFragment.java:79)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.callBack(AbstractBaseFragment.java:100)
	at org.apache.jsp.webcontent.birt.pages.layout.ReportFragment_jsp._jspService(ReportFragment_jsp.java:134)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.service(AbstractBaseFragment.java:79)
	at org.eclipse.birt.report.presentation.aggregation.AbstractBaseFragment.callBack(AbstractBaseFragment.java:100)
	at org.apache.jsp.webcontent.birt.pages.layout.FramesetFragment_jsp._jspService(FramesetFragment_jsp.java:394)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517)
	at org.eclipse.birt.report.presentation.aggregation.layout.FramesetFragment.service(FramesetFragment.java:89)
	at org.eclipse.birt.report.servlet.ViewerServlet.__doGet(ViewerServlet.java:167)
	at org.eclipse.birt.report.servlet.BirtSoapMessageDispatcherServlet.doGet(BirtSoapMessageDispatcherServlet.java:143)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:332)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.eclipse.birt.report.servlet.BirtSoapMessageDispatcherServlet.service(BirtSoapMessageDispatcherServlet.java:115)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.eclipse.birt.report.filter.ViewerFilter.doFilter(ViewerFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.siemens.gms.wsioda.filter.FilterInitialProcessor.doFilter(FilterInitialProcessor.java:201)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.birt.core.exception.CoreException: Invalid javascript expression: ReferenceError: "GMS_init" is not defined. (/report/method[@name="initialize"]#1)
	at org.eclipse.birt.report.engine.javascript.JavascriptEngine.evaluate(JavascriptEngine.java:257)
	at org.eclipse.birt.core.script.ScriptContext.evaluate(ScriptContext.java:132)
	at org.eclipse.birt.report.engine.executor.ExecutionContext.evaluate(ExecutionContext.java:703)
	at org.eclipse.birt.report.engine.executor.ExecutionContext.evaluate(ExecutionContext.java:650)
	at org.eclipse.birt.report.engine.script.internal.ScriptExecutor.handleScriptInternal(ScriptExecutor.java:116)
	at org.eclipse.birt.report.engine.script.internal.ScriptExecutor.handleScript(ScriptExecutor.java:105)
	at org.eclipse.birt.report.engine.script.internal.ReportScriptExecutor.handleInitialize(ReportScriptExecutor.java:74)
	... 155 more
Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "GMS_init" is not defined. (/report/method[@name="initialize"]#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4198)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4176)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4266)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1994)
	at org.mozilla.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2463)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:72)
	at org.mozilla.javascript.gen._report_method__name__initialize___493._c_script_0(/report/method[@name="initialize"]:1)
	at org.mozilla.javascript.gen._report_method__name__initialize___493.call(/report/method[@name="initialize"])
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen._report_method__name__initialize___493.call(/report/method[@name="initialize"])
	at org.mozilla.javascript.gen._report_method__name__initialize___493.exec(/report/method[@name="initialize"])
	at org.eclipse.birt.report.engine.javascript.JavascriptEngine.evaluate(JavascriptEngine.java:250)
	... 161 more

**Comment by speckyspooky** [comment] 2023-04-17 18:34
The error of the ScriptExecutor is due to an issue with the javascript on report level and the variable "GMS_init" is missing.

Currently BIRT use POI-excel-API version 4.1.1 (apache release 2019) but I cannot say when the version was added to BIRT.
Nevertheless if you would have a simple example we would be able to reproduce and debug the problem.

**Comment by speckyspooky** [comment] 2023-06-04 19:34
I will close the issue because the excel creation is possible with the latest version 4.13.
You can open a discussion if you need further support or some hints of your own emitter or additional questions to your scripts.

**Closed by speckyspooky** 2023-06-04 19:34 UTC
